apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: toast
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ose-devops
    name: ose-devops
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ose-devops:latest
    resources: {}
    source:
      git:
        uri: https://bitbucket.org/atosconsulting/allianzdemo
      sourceSecret:
        name: "basicsecret"
      type: Git
    triggers:
    - github:
        secret: zDD5Sx_mQQVF-UdkDJyL
      type: GitHub
    - generic:
        secret: gI3qh_2PwMvIU9YU4u3J
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
